### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ankupsatpute**
Here I have changed from Black to Green

### CODE REVIEW

**Comment by krishnaprasadkeerthi** [comment]
Changes looks good and Peer review is done.

**Review by krishnaprasadkeerthi — CHANGES_REQUESTED** [review]
Change the color from Green to Brown

**Comment by ankupsatpute** [comment]
> Change the color from Green to Brown

Sure  I will start working on changes.

**Comment by ankupsatpute** [comment]
Changes are done kindly review the code.

**Review by krishnaprasadkeerthi — APPROVED** [review]
Changes are approved to checkout from Feature to Dev branch. All set from my end.

**Comment by ankupsatpute** [comment]
Ok , Thanks ..

**Review by krishnaprasadkeerthi — APPROVED** [review]
approved commit 1

**Review by krishnaprasadkeerthi — APPROVED** [review]

**Review by krishnaprasadkeerthi — APPROVED** [review]
done

**Pull request merged**
